version: "3.3"

services:
  web:
    image: "darkkernel/node-api"
    ports:
      - "8000:8080"
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
volumes:
  - mongodb_data_container:dbdata
